apiVersion: v2
name: my-chart
version: 1.0.1
maintainers:
  - name: Elio Marcolino
    email: eliom@jfrog.com
dependencies:
  - name: bitnami/postgresql
    version: 8.10.6
    repository: https://repo.chartcenter.io
